name: font_awesome_pro_flutter
description: |
  Simple, opinionated, code generator for FontAwesome pro icons.

version: 0.0.3
homepage: https://github.com/heftapp/font_awesome_pro_flutter
repository: https://github.com/heftapp/font_awesome_pro_flutter
licence: MIT

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  build: ^2.4.1
  dart_style: ^2.3.2
  code_builder: ^4.5.0
  recase: ^4.1.0
  built_collection: ^5.1.1
  path: ^1.8.3
  glob: ^2.1.2
  analyzer: ^6.1.0

dev_dependencies:
  test: ^1.24.5
  build_test: ^2.2.0
  build_runner: ^2.4.6
